---
title: "Sitzungen"
page-layout: full
toc: false
---

Hier findest du die Folien und R-Skripte zu jeder Sitzung. Folien sind als HTML (für den Browser) und PDF verfügbar.

| Sitzung | Datum | Thema | Schlüsselbegriffe | Pakete | Folien | Skript |
|:-------:|:------|:------|:--------|:-------|:------:|:------|
| 01 | 14.04.2026 | Einführung | Datenanalyse, R, RStudio | `base` | [HTML](slides/sitzung_01_einfuehrung.html) / [PDF](slides/sitzung_01_einfuehrung.pdf) | — |
| 02 | 21.04.2026 | Projekte & Datenimport | Arbeitsverzeichnis, Ordnerstruktur, variable names, variable labels, Codebook | `rio`, `janitor`, `labelled`, `summarytools` | [HTML](slides/sitzung_02_data_import.html) / [PDF](slides/sitzung_02_data_import.pdf) | [Grundlagen](scripts/sitzung_02_grundlagen.R) <br> [Datenimport](scripts/sitzung_02_datenimport.R)|
| 03 | 28.04.2026 | Data Cleaning & Wrangling | Umbennenen, Filtern, Transformieren, Fehlende Werte | `dplyr::count()`, `dplyr::mutate()`, `dplyr::case_when()`, `dplyr::filter()`, `dplyr::select()`, `tidyr:::pivot_wider()` | [HTML](slides/sitzung_03_data_wrangling.html) / [PDF](slides/sitzung_03_data_wrangling.pdf) | [R](scripts/sitzung_03_wrangling.R) |
| 04 | 05.05.2026 | Dataset Merging | Master, unterschiedliche Joins | `dplyr::left_join()` | [HTML](slides/sitzung_04.html) / [PDF](slides/sitzung_04.pdf) | [R](scripts/sitzung_04_merging.R) |
| 05 | 12.05.2026 | Quarto; Deskriptive Statistik – Kennwerte & Visualisierung | Mittelwert, Median, Streuung | `base`, `dplyr`, `ggplot2` | [HTML](slides/sitzung_05_kennwerte.html) / [PDF](slides/sitzung_05_kennwerte.pdf) | [R](scripts/sitzung_05_kennwerte.R) / [Quarto_Beispiel](do_not_render/sitzung_05_kennwerte_beispiel.qmd){.external download="sitzung_05_kennwerte_beispiel.qmd"} |
| 06 | 19.05.2026 | Deskriptive Statistik – Häufigkeits- & Kreuztabellen | Häufigkeiten, Kreuztabellen | `dplyr`, `questionr`, `janitor` | [HTML](slides/sitzung_06_häufigkeiten.html) / [PDF](slides/sitzung_06_häufigkeiten.pdf)  | [R](scripts/sitzung_06_häufigkeiten.R) |
| 07 | 02.06.2026 | Deskriptive Statistik – Schöne Grafiken | Grammar of Graphics, Visualisierung | `ggplot2`, `dplyr` | [HTML](slides/sitzung_07_visualisierung.html) / [PDF](slides/sitzung_07_visualisierung.pdf)  | [R](scripts/sitzung_07_visualisierung.R) ; [Quoten](scripts/Quoten.xlsx)|
| 08 | 09.06.2026 | Deskriptive Statistik – Kreuztabelle & Korrelation | Korrelationskoeffizient, Streudiagramm | `correlation`, `gtsummary` , `gmodels`| [HTML](slides/sitzung_08_zusammenhänge.html) / [PDF](slides/sitzung_08_zusammenhänge.pdf) | [R](scripts/sitzung_08_zusammenhänge.R); [ALLBUS-dfSummary](qmd_dateien/allbus_c_2023_dfSummary.html)  |
| 09 | 16.06.2026 | Inferenzstatistik – Einfache & Multiple Lineare Regression | Regressionskoeffizienten, p-Wert, R² | `stats`, `performance`, `texreg` | [HTML](slides/sitzung_09_regression.html)/ [PDF](slides/sitzung_09_regression.pdf) | [R](scripts/sitzung_09_regressionen.R)  |
| 10 | 23.06.2026 | Regression Diagnostics | Skalenniveau, Exogenität, Unabhängigkeit, Linearität, Heteroskedastizität, Multikollinearität, Ausreißer, Normalverteilung | `stats`, `performance`, `lmtest`, `car` | [HTML](slides/sitzung_10_regressionsvoraussetzungen.html) / [PDF](slides/sitzung_10_regressionsvoraussetzungen.pdf) | [R](scripts/sitzung_10_diagnostics.R) |
| 11 | 30.06.2026 | Logistische Regression | Log-Odds, Odds Ratios, Predicted Probabilities | `stats`, `performance`, `ggeffects`|  [HTML](slides/sitzung_11_logistische_regressionen.html)/ [PDF](slides/sitzung_11_logistische_regressionen.pdf) | —  |
| 12 | 07.07.2026 | Data Analysis Reports | — | — | — / — | —  |
| 13 | 14.07.2026 | Recap | — | — | — / — | —  |
: {.striped .hover tbl-colwidths="[5,10,20,20,15,10,20]"}
