---
title: "Übungen"
toc: false
---

Jede Woche gibt es eine kleine Übungsaufgabe zur Vertiefung des Gelernten. Die Abgabe erfolgt auf [Blackboard](https://fu-berlin.blackboard.com) im Reiter "Abgaben" bis jeweils **Sonntag, 23:59 Uhr** vor der nächsten Sitzung. Sollte es unerwartet zu Problemen mit Blackboard kommen, kann die Übung auch per E-Mail an [maura.kratz@fu-berlin.de](mailto:maura.kratz@fu-berlin.de) eingereicht werden. Die fristgerechte Einreichung der Übungen ist Bestandteil der aktiven und regelmäßigen Teilnahme. 

Unter Materialien findest du zusätzliche Quellen — etwa Lektüre oder Videos - zur Vor- und/ oder Nachbereitung der jeweiligen Sitzung. Die Bearbeitung ist optional. Eine Einreichung ist nicht erforderlich. Wer beim Durcharbeiten merkt, dass die Wiederholung nicht nötig ist, kann sie überspringen.

| Sitzung | Thema | Materialien | Übung | Lösung |
|:-------:|:------|:------------|:-----:|:------:|
| 01 | Einführung | Installiere R und R-Studio! (siehe Folien zu Sitzung 1) | — | — |
| 02 | Projekte & Datenimport | Ein [cheatsheet](materials/cheatsheet_data-import.pdf) zu den unterschiedlichen Datenformaten und wie man sie einlesen kann. | [Übung_01](uebungen/uebung_01_datenimport.R) | [01_Lösung](uebungen/uebung_01_datenimport_loesung.R) |
| 03 | Data Cleaning and Wrangling | Ein [cheatsheet](materials/cheat-sheet_manipulating_data_in_dplyr.pdf) zu den wichtigsten dplyr-Befehlen, sowie zu [tidyr](materials/cheat-sheet_tidyr.pdf) um pivot_wider() besser zu verstehen. | [Übung_02](uebungen/uebung_02_data_wrangling.R) | [02_Lösung](uebungen/uebung_02_data_wrangling_loesung.R) |
| 04 | Dataset Merging | Dasselbe cheatsheet zu den dplyr-Befehlen (siehe oben), diesmal mit Fokus auf "Joining Tables." | [Übung_03](uebungen/uebung_03_data_merging.R) | [03_Lösung](uebungen/uebung_03_data_merging_loesung.R) |
| 05 | Quarto; Deskriptive Statistik – Kennwerte & Visualisierung | Kapitel 1 (bis 1.8) und Kapitel 2 (bis 2.12) im E-Book [Statistik Grundlagen](https://statistikgrundlagen.de/ebook/front-matter/introduction-2/); Ein [Foliensatz](materials/chapter_03_summarize_groupby_ggplot2.pdf) aus dem Datacamp-Kurs "Introduction to the tidyverse" zu den summarize()- und group_by()-Befehlen aus dem dplyr-Paket, sowie Visualisierungsoptionen mit ggplot2. Ein [cheatsheet](materials/cheat-sheet_quarto.pdf) zu Quarto. Alternativ das wichtigste auch in meinem [Quarto-Handout](materials/quarto_handout.pdf).Details findet ihr auch immer auf der [Quarto-Website](https://quarto.org/docs/get-started/hello/rstudio.html) von Posit. | [Übung 04](https://cdn.jsdelivr.net/gh/maurakratz/quanti-methoden-website@main/docs/qmd_dateien/uebung_04_kennwerte.qmd){download="uebung_04_kennwerte.qmd"} (sieht nachher als PDF etwa [so](uebungen/uebung_04_kennwerte.pdf) aus)| [04_Lösung](uebungen/uebung_04_kennwerte_loesung.pdf) |
| 06 | Deskriptive Statistik – Häufigkeitstabellen | [Statistik Grundlagen](https://statistikgrundlagen.de/ebook/front-matter/introduction-2/) Kapitel 3 (nur bis 3.2) | [Übung 05](https://github.com/maurakratz/quanti-methoden-website/raw/main/docs/qmd_dateien/uebung_05_haeufigkeiten.qmd){download="uebung_05_haeufigkeiten.qmd"} | [05_Lösung](qmd_dateien/uebung_05_musterloesung.pdf) |
| 07 | Deskriptive Statistik – Schöne Grafiken | Ein [cheatsheet](materials/data-visualizations-overview.pdf) zu Visualisierungsmöglichkeiten und wann welche am besten passt. | [Übung 06](https://github.com/maurakratz/quanti-methoden-website/raw/main/docs/qmd_dateien/uebung_06_visualisierung.qmd){download="uebung_06_visualisierung.qmd"} | [06_Lösung](qmd_dateien/uebung_06_musterloesung.pdf) |
| 08 | Deskriptive Statistik – Kreuztabellen & Korrelation | [Statistik Grundlagen](https://statistikgrundlagen.de/ebook/chapter/korrelation/) Kapitel 4 (nur bis 4.7) | [Übung 07](https://github.com/maurakratz/quanti-methoden-website/raw/main/docs/qmd_dateien/uebung_07_zusammenhänge.qmd){download="uebung_07_zusammenhänge.qmd"} | — |
| 09 | Inferenzstatistik, Einfache & Multiple Lineare Regression | [Statistik Grundlagen](https://statistikgrundlagen.de/ebook/chapter/regression/) Kapitel 5 zu Regressionen (nur bis 5.6) plus ggf. den [Teil III](https://statistikgrundlagen.de/ebook/part/inferenzstatistik/) zur Inferenzstatistik | — | — |
| 10 | Regression Diagnostics  | [Statistik Grundlagen](https://statistikgrundlagen.de/ebook/chapter/multiple_regression_/) Kapitel 18 | — | — |
| 11 | Logistische Regression | — | — | — |
| 12 | Data Analysis Reports | — | — | — |
| 13 | Recap | — | — | — |
: {.striped .hover tbl-colwidths="[5,25,40,15,15]"}
